# Generated by Django 5.1.1 on 2024-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_diploma_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlightcertificate",
            name="director_name",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="highlightcertificate",
            name="vice_director_name",
            field=models.CharField(default="N/A", max_length=255),
        ),
    ]
