# Generated by Django 5.1.1 on 2024-09-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_highlightcertificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="best_student_certificate_generated",
            new_name="highlight_certificate_generated",
        ),
    ]
