# Generated by Django 5.1.1 on 2024-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_diploma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diploma",
            name="director_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="diploma",
            name="vice_director_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="highlightcertificate",
            name="director_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="highlightcertificate",
            name="vice_director_name",
            field=models.CharField(max_length=255),
        ),
    ]
