services:
  api_certificados:
    build: .
    command: python manage.py runserver ${BACKEND_URL}
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    env_file:
      - .env
    depends_on:
      -  certificados_db

  certificados_db:
    image: postgres:15-alpine
    ports:
      - 3031:${DB_PORT}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
