services:
  api_certificados:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "3030:8000"
    env_file:
      - .env
    depends_on:
      -  certificados_db

  certificados_db:
    image: postgres:15-alpine
    ports:
      - 3031:${DB_PORT}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
